server:
  address: 0.0.0.0
  port: 8080

logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE

spring:
  application:
    name: observapp
  httpclient:
    wiretap: true
    connect-timeout: 1000
    read-timeout: 5s
  httpserver:
    wiretap: true
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600
      routes:
        - id: authentication-service
          uri: ${AUTHENTICATION_SERVICE_URL}
          predicates:
            - Path=/api/a/**
          filters:
            - RewritePath=/api/a/,/

        - id: load-data-service
          uri: ${LOAD_DATA_SERVICE_URL}
          predicates:
            - Path=/api/l/**
          filters:
            - RewritePath=/api/l/,/api/v1/

        - id: metabase-service
          uri: ${METABASE_SERVICE_URL}
          predicates:
            - Path=/metabase/**
          filters:
            - RewritePath=/metabase,/

        - id: section-service
          uri: ${OBSERVAPP_SERVICE_URL}
          predicates:
            - Path=/api/o/**
          filters:
            - RewritePath=/api/o/,/

        - id: users
          uri: ${USERS_SERVICE_URL}
          predicates:
            - Path=/api/u/**
          filters:
            - RewritePath=/api/u/,/

        - id: front
          uri: ${FRONT_SERVICE_URL}
          predicates:
            - Path=/**
          filters:
            - RewritePath=/,/
