server:
  port: 8080

spring:
  cloud:
    gateway:
      httpclient:
        ssl:
          use-insecure-trust-manager: true
      routes:
        - id: authentication-service
          uri: http://authentication
          predicates:
            - Path=/auth/v1/**
          filters:
            - RewritePath=/auth/v1,/
        - id: metabase-service
          uri: http://metabase:3000
          predicates:
            - Path=/metabase/**
          filters:
            - RewritePath=/metabase,/

        - id: section-service
          uri: http://observapp
          predicates:
            - Path=/observapp/v1/**
          filters:
            - RewritePath=/observapp/v1,/

        - id: users
          uri: http://users
          predicates:
            - Path=/users-managment/v1/**
          filters:
            - RewritePath=/users-managment/v1,/
